export  const FORMULARIO_PROJECT = 'FORMULARIO_PROJECT'
export  const GET_PROJECTS = 'GET_PROJECTS'
export  const ADD_NEWPROJECT = 'ADD_NEWPROJECT'
export  const FORM_VALIDATE = 'FORM_VALIDATE'
export  const CURRENT_PROJECT = ' CURRENT_PROJECT'
export  const DELETE_PROJECT = ' DELETE_PROJECT'

export const ERROR_PROJECT = 'ERROR_PROJECT'

export const TASKS_PROJECT = 'TASKS_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const TASK_VALIDATE = 'TASK_VALIDATE'
export const DELETE_TASK = ' DELETE_TASK'
// export const STATUS_TASK = 'STATUS_TASK'
export const CURRENT_TASK = 'CURRENT_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const CLEAN_TASK = 'CLEAN_TASK'

export const ALERT_SHOW = 'ALERT_SHOW'
export const ALERT_HIDDEN = 'ALERT_HIDDEN'

export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const RETRIEVE_USER = 'RETRIEVE_USER'
export const RETRIEVE_USER_FAILED = 'RETRIEVE_USER_FAILED'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const CLOSE_SESSION = 'CLOSE_SESSION'

